# Generated by Django 5.0.7 on 2024-07-18 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_transfare_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accounts",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="transactions",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactions",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="accounts",
            name="balance",
            field=models.DecimalField(decimal_places=10, max_digits=100),
        ),
        migrations.AlterField(
            model_name="accounts",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="accounts",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="amount",
            field=models.DecimalField(decimal_places=10, max_digits=100),
        ),
    ]
