# Generated by Django 5.0.7 on 2024-07-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_transfare_app', '0003_alter_accounts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='receiver_balance_before_transaction',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender_balance_before_transaction',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='balance',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
    ]
