# Generated by Django 5.0.7 on 2024-07-20 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_transfare_app', '0005_alter_transactions_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='transactions',
            name='receiver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='account_transfare_app.accounts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='account_transfare_app.accounts'),
            preserve_default=False,
        ),
    ]
